### PR TITLE
improving consistency with `let` vs `const`

### PR DESCRIPTION
**Pull request by thennothinghappened**
Using `let` everywhere is pretty confusing and obfuscates where its actually needed, it also tends to be better in JS to use `===` wherever possible.

I've tested locally and was looking out for any cases where the original used `==`/`!=` that changing could've changed the behaviour, but as far as I can see, I'm not aware of any edge cases this comes into play.

### CODE REVIEW

**Comment by YellowAfterlife** [comment]
Thank you for your contribution, though what this plugin really needs is a complete rewrite using Igor instead of GMAssetCompiler.

I do not generally use `const` (or `final` in languages that use that) for local variables unless something absolutely shouldn't be touched and cannot realistically promise that future code here will be held to such a high standard, especially since all of my ongoing work to update this plugin is like trying to repair a hole in a ship's hull with adhesive tape - it is but a matter of time until it completely falls apart.

As for changing `==` to `===`, that is not a good idea and is not worth what little performance benefit it might offer. Without running the code, I can tell you that [this](https://github.com/YAL-GMEdit/builder/pull/5/commits/d543f02d981f32454b0c41017aeb7e7adfbe6ae8#diff-7d111b05fe05c50beb729d1e99a36010fbda8c89b57a1a26ac3e7b0778a0ed53R175) will break error reporting because obj[missing key] will yield `undefined` and not `null`.

**Comment by thennothinghappened** [comment]
> Thank you for your contribution, though what this plugin really needs is a complete rewrite using Igor instead of GMAssetCompiler.
> 
> I do not generally use `const` (or `final` in languages that use that) for local variables unless something absolutely shouldn't be touched and cannot realistically promise that future code here will be held to such a high standard, especially since all of my ongoing work to update this plugin is like trying to repair a hole in a ship's hull with adhesive tape - it is but a matter of time until it completely falls apart.
> 
> As for changing `==` to `===`, that is not a good idea and is not worth what little performance benefit it might offer. Without running the code, I can tell you that [this](https://github.com/YAL-GMEdit/builder/pull/5/commits/d543f02d981f32454b0c41017aeb7e7adfbe6ae8#diff-7d111b05fe05c50beb729d1e99a36010fbda8c89b57a1a26ac3e7b0778a0ed53R175) will break error reporting because obj[missing key] will yield `undefined` and not `null`.

Fair enough, this PR overall was a lot of going in and changing it to what felt more readable myself. As for GMAssetCompiler, I was actually pretty curious if there was a specific reason for that, as using Igor took me just a minute to get running and doing the same thing from the commandline.

I'd be interested in making a completely new plugin serving the same purpose built around Igor instead, from what I've seen something basic that can do that doesn't seem overly complicated.

**Comment by YellowAfterlife** [comment]
Igor takes environment variables (desired platform, project directory, settings, and so on) and invokes GMAssetCompiler while handling all of the related setup (like calling pre-build/post-build scripts, managing temp directories, and so on).

For example, adding YYC support to builder is a struggle, but with Igor that'd be one extra flag (IIRC).

**Comment by thennothinghappened** [comment]
Another interesting thing on builder I've noticed is it displays the "Made with GameMaker" splash, Igor's build did not (by default, I'd assume).

**Comment by YellowAfterlife** [comment]
I've never seen a splash on my end when using builder so that's just another example of why doing it this way is not a good idea

**Pull request closed without merging**
